@startuml

participant "Webová kamera"
participant "HandRecognition"
participant "MediaPipe Hands"
participant "GestureRecognition"
participant "Hra"

"Webová kamera" -> "HandRecognition" : Pošle snímek
"HandRecognition" -> "MediaPipe Hands" : Snímek
"MediaPipe Hands" -> "HandRecognition" : Pozice bodů
"HandRecognition" -> "GestureRecognition" : HandLandmark
"GestureRecognition" -> "Hra" : Rozpoznané gesto

@enduml