@startuml

participant "Webová kamera"
participant "HandRecognition"
participant "MediaPipe Hands"
participant "GestureRecognition"
participant "Výsledek"

"Webová kamera" -> "HandRecognition" : Pošle snímek
"HandRecognition" -> "MediaPipe Hands" : Snímek
"MediaPipe Hands" -> "HandRecognition" : HandLandmark
"HandRecognition" -> "GestureRecognition" : HandLandmark
"GestureRecognition" -> "Výsledek" : Rozpoznané gesto

@enduml