@startuml
left to right direction

[*] --> CONNECTED
CONNECTED --> PLAYING : Palec nahoru
PLAYING --> SUBMITTED : Uběhl čas
SUBMITTED --> WINNER
SUBMITTED --> LOSER
SUBMITTED --> TIED
WINNER --> [*]
LOSER --> [*]
TIED --> [*]

@enduml